# https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: Swift

on:
  push:
    branches: [ "master", "dev", "tmp" ]
    
jobs:
  build:
    name: Swift
    strategy:
      matrix:
        os: [ubuntu-latest]
        swift: ["5.x"]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: swift-actions/setup-swift@65540b95f51493d65f5e59e97dcef9629ddf11bf
        with:
          swift-version: ${{ matrix.swift }}
      - uses: actions/checkout@v4
      - name: Get swift version
        run: swift --version
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test

